DRIVER_PATH = '/Users/giovannoni/selenium/drivers/chromedriver'
BROWSER_USER_PATH = './test-profile'
DEFAULT_USER = 'Vernalhav'
DEFAULT_REPO = 'github-issue-tracker'
SCREENSHOTS_DIR = './screenshots'
PDF_DIR = './pdfs'
